config/routes.rb
Rails.application.routes.draw do
  root "nogizakas#login_check"

  devise_for :users, controllers: {
    registrations: "nogimasas/registrations",
    sessions: "nogimasas/sessions"
  }

  get "nogizakas/login_check"
  get "nogizakas/privacy"
  get "nogizakas/terms"
  get "nogizakas/contact"
  post "nogizakas/guest_sign_in"

  get "nogitops", to: "nogitops#index"
  
  get "posts", to: "posts#index"

  #2012
  get "posts/2012", to:"posts#two"
  get "posts/2012/konno", to:"posts#konno"
  get "posts/new_konno", to: "posts#new_konno"
  post "posts/new_konno", to: "posts#create_konno"
  get "posts/2012/zepptokyo", to:"posts#zepptokyo"
  get "posts/new_zepptokyo", to: "posts#new_zepptokyo"
  post "posts/new_zepptokyo", to: "posts#create_zepptokyo"
  #2013
  get "posts/2013", to:"posts#three"
  get "posts/2013/first", to:"posts#first"
  get "posts/new_first", to: "posts#new_first"
  post "posts/new_first", to: "posts#create_first"
  get "posts/2013/three_summer_sapporo", to:"posts#three_summer_sapporo"
  get "posts/new_three_summer_sapporo", to: "posts#new_three_summer_sapporo"
  post "posts/new_three_summer_sapporo", to: "posts#create_three_summer_sapporo"
  get "posts/2013/three_summer_fukuoka", to:"posts#three_summer_fukuoka"
  get "posts/new_three_summer_fukuoka", to: "posts#new_three_summer_fukuoka"
  post "posts/new_three_summer_fukuoka", to: "posts#create_three_summer_fukuoka"
  get "posts/2013/three_summer_osaka", to:"posts#three_summer_osaka"
  get "posts/new_three_summer_osaka", to: "posts#new_three_summer_osaka"
  post "posts/new_three_summer_osaka", to: "posts#create_three_summer_osaka"
  get "posts/2013/three_summer_nagoya", to:"posts#three_summer_nagoya"
  get "posts/new_three_summer_nagoya", to: "posts#new_three_summer_nagoya"
  post "posts/new_three_summer_nagoya", to: "posts#create_three_summer_nagoya"
  get "posts/2013/three_summer_tokyo", to:"posts#three_summer_tokyo"
  get "posts/new_three_summer_tokyo", to: "posts#new_three_summer_tokyo"
  post "posts/new_three_summer_tokyo", to: "posts#create_three_summer_tokyo"
  get "posts/2013/three_summer_final", to:"posts#three_summer_final"
  get "posts/new_three_summer_final", to: "posts#new_three_summer_final"
  post "posts/new_three_summer_final", to: "posts#create_three_summer_final"
  get "posts/2013/three_xmas", to:"posts#three_xmas"
  get "posts/new_three_xmas", to: "posts#new_three_xmas"
  post "posts/new_three_xmas", to: "posts#create_three_xmas"
  #2014
  get "posts/2014", to:"posts#four"
  get "posts/2014/second", to:"posts#second"
  get "posts/new_second", to: "posts#new_second"
  post "posts/new_second", to: "posts#create_second"
  get "posts/2014/four_under", to:"posts#four_under"
  get "posts/new_four_under", to: "posts#new_four_under"
  post "posts/new_four_under", to: "posts#create_four_under"
  get "posts/2014/four_summer_osaka", to:"posts#four_summer_osaka"
  get "posts/new_four_summer_osaka", to: "posts#new_four_summer_osaka"
  post "posts/new_four_summer_osaka", to: "posts#create_four_summer_osaka"
  get "posts/2014/four_summer_fukuoka", to:"posts#four_summer_fukuoka"
  get "posts/new_four_summer_fukuoka", to: "posts#new_four_summer_fukuoka"
  post "posts/new_four_summer_fukuoka", to: "posts#create_four_summer_fukuoka"
  get "posts/2014/four_summer_sendai", to:"posts#four_summer_sendai"
  get "posts/new_four_summer_sendai", to: "posts#new_four_summer_sendai"
  post "posts/new_four_summer_sendai", to: "posts#create_four_summer_sendai"
  get "posts/2014/four_summer_nagoya", to:"posts#four_summer_nagoya"
  get "posts/new_four_summer_nagoya", to: "posts#new_four_summer_nagoya"
  post "posts/new_four_summer_nagoya", to: "posts#create_four_summer_nagoya"
  get "posts/2014/four_summer_tokyo", to:"posts#four_summer_tokyo"
  get "posts/new_four_summer_tokyo", to: "posts#new_four_summer_tokyo"
  post "posts/new_four_summer_tokyo", to: "posts#create_four_summer_tokyo"
  get "posts/2014/four_under_second", to:"posts#four_under_second"
  get "posts/new_four_under_second", to: "posts#new_four_under_second"
  post "posts/new_four_under_second", to: "posts#create_four_under_second"
  get "posts/2014/four_under_xmas", to:"posts#four_under_xmas"
  get "posts/new_four_under_xmas", to: "posts#new_four_under_xmas"
  post "posts/new_four_under_xmas", to: "posts#create_four_under_xmas"
  get "posts/2014/four_xmas", to:"posts#four_xmas"
  get "posts/new_four_xmas", to: "posts#new_four_xmas"
  post "posts/new_four_xmas", to: "posts#create_four_xmas"

  #2015
  get "posts/2015", to:"posts#five"
  get "posts/2015/third", to:"posts#third"
  get "posts/new_third", to: "posts#new_third"
  post "posts/new_third", to: "posts#create_third"
  get "posts/2015/five_summer_sendai", to: "posts#five_summer_sendai"
  get "posts/new_five_summer_sendai", to: "posts#new_five_summer_sendai"
  post "posts/new_five_summer_sendai", to: "posts#create_five_summer_sendai"
  get "posts/2015/five_summer_nagoya", to: "posts#five_summer_nagoya"
  get "posts/new_five_summer_nagoya", to: "posts#new_five_summer_nagoya"
  post "posts/new_five_summer_nagoya", to: "posts#create_five_summer_nagoya"
  get "posts/2015/five_summer_hirosima", to: "posts#five_summer_hirosima"
  get "posts/new_five_summer_hirosima", to: "posts#new_five_summer_hirosima"
  post "posts/new_five_summer_hirosima", to: "posts#create_five_summer_hirosima"
  get "posts/2015/five_summer_fukuoka", to: "posts#five_summer_fukuoka"
  get "posts/new_five_summer_fukuoka", to: "posts#new_five_summer_fukuoka"
  post "posts/new_five_summer_fukuoka", to: "posts#create_five_summer_fukuoka"
  get "posts/2015/five_summer_osaka", to: "posts#five_summer_osaka"
  get "posts/new_five_summer_osaka", to: "posts#new_five_summer_osaka"
  post "posts/new_five_summer_osaka",to: "posts#create_five_summer_osaka"
  get "posts/2015/five_summer_tokyo", to: "posts#five_summer_tokyo"
  get "posts/new_five_summer_tokyo", to: "posts#new_five_summer_tokyo"
  post "posts/new_five_summer_tokyo", to: "posts#create_five_summer_tokyo"
  get "posts/2015/five_under_four", to: "posts#five_under_four"
  get "posts/new_five_under_four", to: "posts#new_five_under_four"
  post "posts/new_five_under_four", to: "posts#create_five_under_four"
  get "posts/2015/five_under_budo", to: "posts#five_under_budo"
  get "posts/new_five_under_budo", to: "posts#new_five_under_budo"
  post "posts/new_five_under_budo", to: "posts#create_five_under_budo"
  get "posts/2015/five_xmas", to: "posts#five_xmas"
  get "posts/new_five_xmas", to: "posts#new_five_xmas"
  post "posts/new_five_xmas", to: "posts#create_five_xmas"

  #2016
  get "posts/2016", to:"posts#six"
  get "posts/2016/seira", to: "posts#seira"
  get "posts/new_seira", to: "posts#new_seira"
  post "posts/new_seira", to: "posts#create_seira"
  get "posts/2016/six_under_tohoku", to: "posts#six_under_tohoku"
  get "posts/new_six_under_tohoku", to: "posts#new_six_under_tohoku"
  post "posts/new_six_under_tohoku", to: "posts#create_six_under_tohoku"
  get "posts/2016/maimai", to: "posts#maimai"
  get "posts/new_maimai", to: "posts#new_maimai"
  post "posts/new_maimai", to: "posts#create_maimai"
  get "posts/2016/six_summer_osaka", to: "posts#six_summer_osaka"
  get "posts/new_six_summer_osaka", to: "posts#new_six_summer_osaka"
  post "posts/new_six_summer_osaka", to: "posts#create_six_summer_osaka"
  get "posts/2016/six_summer_nagoya", to: "posts#six_summer_nagoya"
  get "posts/new_six_summer_nagoya", to: "posts#new_six_summer_nagoya"
  post "posts/new_six_summer_nagoya", to: "posts#create_six_summer_nagoya"
  get "posts/2016/six_summer_sendai", to: "posts#six_summer_sendai"
  get "posts/new_six_summer_sendai", to: "posts#new_six_summer_sendai"
  post "posts/new_six_summer_sendai", to: "posts#create_six_summer_sendai"
  get "posts/2016/six_summer_fukuoka", to: "posts#six_summer_fukuoka"
  get "posts/new_six_summer_fukuoka", to: "posts#new_six_summer_fukuoka"
  post "posts/new_six_summer_fukuoka", to: "posts#create_six_summer_fukuoka"
  get "posts/2016/six_summer_tokyo", to: "posts#six_summer_tokyo"
  get "posts/new_six_summer_tokyo", to: "posts#new_six_summer_tokyo"
  post "posts/new_six_summer_tokyo", to: "posts#create_six_summer_tokyo"
  get "posts/2016/six_under_tyugoku", to: "posts#six_under_tyugoku"
  get "posts/new_six_under_tyugoku", to: "posts#new_six_under_tyugoku"
  post "posts/new_six_under_tyugoku", to: "posts#create_six_under_tyugoku"
  get "posts/2016/six_senbatu_xmas", to: "posts#six_senbatu_xmas"
  get "posts/new_six_senbatu_xmas", to: "posts#new_six_senbatu_xmas"
  post "posts/new_six_senbatu_xmas", to: "posts#create_six_senbatu_xmas"
  get "posts/2016/six_under_xmas", to: "posts#six_under_xmas"
  get "posts/new_six_under_xmas", to: "posts#new_six_under_xmas"
  post "posts/new_six_under_xmas", to: "posts#create_six_under_xmas"

  #2017
  get "posts/2017", to:"posts#seven"
  get "posts/2017/univ", to: "posts#univ"
  get "posts/new_univ", to: "posts#new_univ"
  post "posts/new_univ", to: "posts#create_univ"
  get "posts/2017/fifth", to: "posts#fifth"
  get "posts/new_fifth", to: "posts#new_fifth"
  post "posts/new_fifth", to: "posts#create_fifth"
  get "posts/2017/under_tokyo", to: "posts#under_tokyo"
  get "posts/new_under_tokyo", to: "posts#new_under_tokyo"
  post "posts/new_under_tokyo", to: "posts#create_under_tokyo"
  get "posts/2017/sanki", to: "posts#sanki"
  get "posts/new_sanki", to: "posts#new_sanki"
  post "posts/new_sanki", to: "posts#create_sanki"
  get "posts/2017/seven_summer_tokyo", to: "posts#seven_summer_tokyo"
  get "posts/new_seven_summer_tokyo", to: "posts#new_seven_summer_tokyo"
  post "posts/new_seven_summer_tokyo", to: "posts#create_seven_summer_tokyo"
  get "posts/2017/seven_summer_sendai", to: "posts#seven_summer_sendai"
  get "posts/new_seven_summer_sendai", to: "posts#new_seven_summer_sendai"
  post "posts/new_seven_summer_sendai", to: "posts#create_seven_summer_sendai"
  get "posts/2017/seven_summer_osaka", to: "posts#seven_summer_osaka"

app/models/nogizaka.rb
class Nogizaka < ApplicationRecord
  belongs_to :user
  validates :age, presence: true
  validates :member, presence: true
  validates :song, presence: true  
end

app/controllers/nogizakas_controller.rb
class NogizakasController < ApplicationController
  PER=25
  
  def index
    @data=Account.order(:created_at).page(params[:page]).per(PER)
    @like=Like.new
  end

  def login
  end

  def login_check
    render :layout => "top"
  end

  def show
    @data=Account.find(params[:id])
  end

  def new
    @account=Account.new
  end

  def create
    if Account.where(name: current_user.username).blank?
      @account=Account.new(account_params)
      if @account.save
        redirect_to nogizakas_path
      else
        render "new"
      end 
    end
  end

  def edit
    @account=Account.find(params[:id])
  end

  def update
    obj=Account.find(params[:id])
    obj.update(account_params)
    redirect_to nogizakas_path
  end

  def guest_sign_in
    guest = User.find_or_create_by!(username: "ゲストユーザー") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
    if sign_in guest 
      Account.find_or_create_by!(name: "ゲストユーザー") do |account|
        account.age=20
        account.member="秋元真夏"
        account.song="ぐるぐるカーテン"
        account.introduction="ゲストユーザーです。"
        account.user_id=current_user.id
      end
    end
    redirect_to nogitops_path
  end

  private
  def account_params
    params.require(:account).permit(:name, :age, :member, :song, :introduction).merge(user_id: current_user.id)
  end
end

app/helpers/nogizakas_helper.rb
module NogizakasHelper
end

app/views/nogizakas/contact.html.erb
<h1 class=" text-white">Nogiステ(乃木坂46 LiveStation)</h1>
<p style="margin-top: 100px;">サービスに関するお問い合わせ・要望は管理人<a href="">Twitter</a>のリプライ・DMにてお願い致します。</p>

app/views/nogizakas/destroy.html.erb
<h2 class="text-white" style="padding-top: 10px;">アカウント削除</h2>    
<p class="photo" style="text-align: right;"><a href="/nogizakas">ユーザー一覧へ>></a></p>    
<table class="table" style="margin-top: 50px;">
    <tr><th>ユーザー名</th><td><%= @data.name %></td></tr>
    <tr><th>年齢</th><td><%= @data.age %></td></tr>
    <tr><th>推しメン</th><td><%= @data.member %></td></tr>
    <tr><th>好きな楽曲</th><td><%= @data.song %></td></tr>
    <tr><th>自己紹介</th><td><%= @data.introduction %></td></tr>
</table>
<%= form_tag controller: "nogizakas", action: "destroy" do%>
    <%= hidden_field_tag "id", {value: @account.id} %>
    <input type="submit" name="destroy" value="削除" class="btn btn-primary">
<% end %>

app/views/nogizakas/edit.html.erb
<h2 class="text-white" style="padding-top: 10px;">アカウント編集</h2>
<p class="photo" style="text-align: right;"><a href="/nogizakas">ユーザー一覧へ>></a></p>
<%= form_for(@account, url:{controller:"nogizakas", action:"update"}) do |form| %>
    <div class="form-group">
        <label for="name">ユーザー名</label>
        <%= form.hidden_field :name, :value=>current_user.username, class: "form-control" %>
        <p><%= current_user.username %></p>
    </div>
    <div class="form-group">
        <label for="age">年齢</label>
        <div>
            <%= form.select :age, [["15","15"],["16","16"],["17","17"],["18","18"],["19","19"],["20","20"],["21","21"],["22","22"],["23","23"],["24","24"],["25","25"],["26","26"],["27","27"],["28","28"],["29","29"],["30","30"],["31","31"],["32","32"],["33","33"],["34","34"],["35","35"],["36","36"],["37","37"],["38","38"],["39","39"],["40","40"],["41","41"],["42","42"],["43","43"],["44","44"],["45","45"],["46","46"],["47","47"],["48","48"],["49","49"],["50","50"],["51","51"],["52","52"],["53","53"],["54","54"],["55","55"],["56","56"],["57","57"],["58","58"],["59","59"],["60","60"],["61","61"],["62","62"],["63","63"],["64","64"],["65","65"]], {include_blank: "選択して下さい"}, {class: "form-control"} %>
        </div>
    </div>
    <div class="form-group">
        <label for="member">推しメン</label>
        <div>
            <%= form.select :member, [["秋元真夏","秋元真夏"],["生田絵梨花","生田絵梨花"],["伊藤純奈","伊藤純奈"],["伊藤理々杏","伊藤理々杏"],["岩本蓮加","岩本蓮加"],["梅澤美波","梅澤美波"],["大園桃子","大園桃子"],["北野日奈子","北野日奈子"],["久保史緒里","久保史緒里"],["齋藤飛鳥","齋藤飛鳥"],["阪口珠美","阪口珠美"],["佐藤楓","佐藤楓"],["新内眞衣","新内眞衣"],["鈴木絢音","鈴木絢音"],["高山一実","高山一実"],["寺田蘭世","寺田蘭世"],["中村麗乃","中村麗乃"],["樋口日奈","樋口日奈"],["星野みなみ","星野みなみ"],["向井葉月","向井葉月"],["山崎怜奈","山崎怜奈"],["山下美月","山下美月"],["吉田綾乃クリスティー","吉田綾乃クリスティー"],["与田祐希","与田祐希"],["渡辺みり愛","渡辺みり愛"],["和田まあや","和田まあや"],["遠藤さくら","遠藤さくら"],["賀喜遥香","賀喜遥香"],["掛橋沙耶香","掛橋沙耶香"],["金川紗耶","金川紗耶"],["北川悠理","北川悠理"],["黒見明香","黒見明香"],["佐藤璃果","佐藤璃果"],["柴田柚菜","柴田柚菜"],["清宮レイ","清宮レイ"],["田村真佑","田村真佑"],["筒井あやめ","筒井あやめ"],["早川聖来","早川聖来"],["林瑠奈","林瑠奈"],["松尾美佑","松尾美佑"],["矢久保美緒","矢久保美緒"],["弓木奈於","弓木奈於"]], {include_blank: "選択して下さい"}, {class: "form-control"} %>
        </div>
    </div>
    <div class="form-group">
        <label for="song">好きな楽曲</label>
        <div>
            <%= form.select :song, [["ぐるぐるカーテン","ぐるぐるカーテン"],["おいでシャンプー","おいでシャンプー"],["走れ！Bicycle","走れ！Bycycle"],["制服のマネキン","制服のマネキン"],["君の名は希望","君の名は希望"],["ガールズルール","ガールズルール"],["バレッタ","バレッタ"],["気づいたら片思い","気づいたら片思い"],["夏のFree&Easy","夏のFree&Easy"],["何度目の青空か？","何度目の青空か？"],["命は美しい","命は美しい"],["太陽ノック","太陽ノック"],["今、話したい誰かがいる","今、話したい誰かがいる"],["ハルジオンが咲く頃","ハルジオンが咲く頃"],["裸足でSummer","裸足でSummer"],["サヨナラの意味","サヨナラの意味"],["インフルエンサー","インフルエンサー"],["逃げ水","逃げ水"],["いつかできるから今日できる","いつかできるから今日できる"],["シンクロニシティ","シンクロニシティ"],["ジコチューで行こう！","ジコチューで行こう！"],["帰り道は遠回りしたくなる","帰り道は遠回りしたくなる"],["Sing Out!","Sing Out!"],["夜明けまで強がらなくていい","夜明けまで強がらなくていい"],["しあわせの保護色","しあわせの保護色"],["僕は僕を好きになる","僕は僕を好きになる"],["ごめんねFingers crossed","ごめんねFingers crossed"]], {include_blank: "選択して下さい"}, {class: "form-control"}%>
        </div>
    </div>
    <div class="form-group">
        <label for="introduction">自己紹介</label>
        <%= form.text_area :introduction, class:"form-control" %>
    </div>
    <%= form.submit "編集", class:"btn btn-primary" %>
<% end %>

app/views/nogizakas/index.html.erb
<h2 class="text-white" style="padding-top: 10px;">ユーザー一覧</h2>
<p class="photo" style="text-align: right;"><a href="/nogitops">トップページへ>></a></p>
<div style="clear: both; text-align: center;">  
    <table class="table" style="margin-top: 30px;">
        <tr>
            <th>ユーザー名</th><th>年齢</th><th>推しメン</th><th>好きな楽曲</th><th>投稿数</th><th colspan="1"></th>
        </tr>
        <% @data.each do |obj| %>
            <tr>
                <td><a href="/nogizakas/<%= obj.id %>" style="color: purple;"><%= obj.name %></a></td>
                <td><%= obj.age %></td>
                <td><%= obj.member %></td>
                <td><%= obj.song %></td>
                <td><%= obj.user.posts.joins(:images).count %></td>
                <% if obj.user.username==current_user.username || current_user.admin? %>
                    <td><a href="/nogizakas/<%= obj.id%>/edit" style="color: purple;">編集</a></td>
                <% end %>
            </tr>
        <% end %>
    </table>
    <div><%= paginate @data %></div>
</div>

<script>

</script>

app/views/nogizakas/login_check.html.erb
<h1 class="text-white">乃木ステ(乃木坂46 LiveStation)</h1>
<p class="text-white">ようこそゲストさん！</p>
<h4 class="description" style="font-size: 28px; text-align: center;">あの時のLIVEに行きたいあなたへ<br>過去の乃木坂LIVEに関連した写真を投稿してファンでシェアするサービス</h4>
<h5 class="enter" style="margin-top: 50px; text-align: center;"><%=link_to "ログイン&gt;&gt;".html_safe, new_user_session_path, :style=>"color: white;" %></h5>
<h5 class="signup" style="margin-top: 40px; text-align: center;"><%= link_to "新規登録&gt;&gt;".html_safe, new_user_registration_path, :style=>"color: white;"  %></h5>
<h5 class="signout" style="margin-top: 40px; text-align: center;"><%= link_to "ログアウト&gt;&gt;".html_safe, destroy_user_session_path, method: :delete, :style=>"color: white;" %></h5>
<h5 class="guest" style="margin-top: 40px; text-align: center;"><%= link_to "お試しログイン&gt;&gt;".html_safe, nogizakas_guest_sign_in_path, method: :post, :style=>"color: white;"  %></h5>

app/views/nogizakas/show.html.erb
<h2 class="text-white" style="padding-top: 10px;">個人プロフィール</h2>
<p class="photo" style="text-align: right;"><a href="/nogizakas">ユーザー一覧へ>></a></p>    
<table class="table text-black" style="margin-top: 50px;">
    <tr><th>ユーザー名</th><td><%= @data.name %></td></tr>
    <tr><th>年齢</th><td><%= @data.age %></td></tr>
    <tr><th>推しメン</th><td><%= @data.member %></td></tr>
    <tr><th>好きな楽曲</th><td><%= @data.song %></td></tr>
    <tr><th>投稿数</th><td><%= @data.user.posts.joins(:images).count %></td></tr>
    <tr><th>自己紹介</th><td><%= @data.introduction %></td></tr>
</table>